apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/*
build:
  local:
    push: false
  artifacts:
    - image: liran1789/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: liran1789/client-bank
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: liran1789/transactions
      context: transactions
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .