apiVersion: apps/v1
kind: Deployment
metadata:
  name: accommodations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accommodations
  template:
    metadata:
      labels:
        app: accommodations
    spec:
      containers:
        - name: accommodations
          image: liran1789/accommodations
          env:
            - name: DATABASE_URL
              value: 'postgresql://safeharbor:asdf@accommodations-postgres-srv:5432/accommodations'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: safe-harbor
            - name: QUEUE_GROUP_NAME
              value: 'accommodations-service'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NODE_ENV
              value: 'production'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: accommodations-srv
spec:
  selector:
    app: accommodations
  ports:
    - name: accommodations
      protocol: TCP
      port: 3000
      targetPort: 3000