apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: liran1789/transactions
          env:
            - name: DATABASE_URL
              value: 'postgresql://bankuser:asdf@transactions-postgres-srv:5432/transactions'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: bank
            - name: QUEUE_GROUP_NAME
              value: 'transactions-service'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/transactions/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-srv
spec:
  selector:
    app: transactions
  ports:
    - name: transactions
      protocol: TCP
      port: 3000
      targetPort: 3000